### ISSUE TITLE
Long SMS not supported

### ISSUE THREAD

**Issue by HankAviator** [iptux/android_device_xiaomi_mione_plus#27]
SMS > 160 Latin letters or >70 other letters, are not able to be sent in one whole SMS.

**Comment by iptux** [comment]
https://github.com/iptux/android_device_xiaomi_mione_plus/commits/cm-11.0/overlay/packages/apps/Mms/res/xml/mms_config.xml

**Comment by HankAviator** [comment]
on current cm-11 all apps fail to send as whole, but may send if splitted.
