### ISSUE TITLE
Touch focus & light metering not working (Camera)

### ISSUE THREAD

**Issue by HankAviator** [iptux/android_device_xiaomi_mione_plus#28]
Attempted on lateset version of Snap

**Comment by BambooIV** [comment]
@iptux 
https://github.com/iptux/android_device_xiaomi_msm8660-common/tree/jb-7.8/camerawrapper

'camerawrapper' named to 'camera',as cm did

https://github.com/CyanogenMod/android_device_samsung_msm8660-common/tree/cm-11.0/camera

**Comment by HankAviator** [comment]
Thanks for your efforts for maintaining xiaomi mi-one plus cm11. I have purchased a new phone and therefore not subscribing this device.
