### ISSUE TITLE
boot on cm10.1 using 3.4 kernel

### ISSUE THREAD

**Issue by iptux** [iptux/android_device_xiaomi_mione_plus#3]

**Comment by PeterCxy** [comment]
Can it show the Cyanogenmod Logo animation?

**Comment by iptux** [comment]
yes, but no display

**Comment by iptux** [comment]
https://github.com/iptux/android_device_xiaomi_mione_plus/commit/41d5b9d7ae45e13695095e566421d6687fc18306

**Comment by iptux** [comment]
see jb-k3.4 (for cm-10.1) and jb-7.7 (for cm-10.2) branch
