### ISSUE TITLE
Xiaomi is open MI 1/1S kernel source code, can you use open source kernel?

### ISSUE THREAD

**Issue by jason-akw** [iptux/android_device_xiaomi_mione_plus#34]
Xiaomi is open MI 1/1S kernel source code, can you use open source kernel?

**Comment by iptux** [comment]
I'm using it in CM11 3.4 kernel building, see https://github.com/iptux/local_manifests/blob/master/cm-11.0-for-mione_plus-with-3.4-kernel.xml#L6

3.0 kernel source is still unavailable, so prebuilt kernel is used
