### ISSUE TITLE
SmartisanOS may help porting mi1 and mi2

### ISSUE THREAD

**Issue by iptux** [iptux/android_device_xiaomi_mione_plus#6]
SmartisanOS is CyanogenMod based, and it will be a fully working ROM with supporting from xiaomi, so it may help porting, how do you tkink guys?
@ivan19871002 @shendu @ShenduOS @airk000

**Comment by lkv1988** [comment]
咱们是不是可以说中文……@iptux

**Comment by iptux** [comment]
Smartisan OS don't have official support for mi1
