### ISSUE TITLE
phone call and mobile data not available under cdma (M1C1)

### ISSUE THREAD

**Issue by iptux** [iptux/android_device_xiaomi_mione_plus#7]
seems fixed by [shendu](https://github.com/ShenduOS/android_device_xiaomi_mione-plus/commit/8f68b84b555ec3b2f78c37ff178e10fa284e102a), but need to be tested

and hardcoded operator is not a good choice

**Comment by github-wang** [comment]
这个拨号未知不是cm已经修复了吗？

**Comment by github-wang** [comment]
理解错了！对不起！
